GET http://localhost:8080/vc/query
Authorization: 123456789
Content-Type: application/json

{
  "page": "[2:3]"
}

###

POST http://localhost:8080/vc/find_player
Authorization: m7X9p2K4zR6Q3bA8
Content-Type: application/json

{
  "name": "bulefire_fox"
}

###

POST http://localhost:8080/vc/hh
Authorization: 123456789
Content-Type: application/json

{
  "qID":"ABCD123",
  "message": "hh"
}

###
POST http://localhost:8080/vc/blind
Authorization: 123456789
Content-Type: application/json

{

  "qqID":"ABCD123",
  "code": "D98N8VFD"
}