POST http://localhost:8080/vc/query
Authorization: 123456789
Content-Type: application/json

{
  "server": "all",
  "page": 0
}

###

POST http://localhost:8080/vc/find_player
Authorization: 123456789
Content-Type: application/json

{
  "name": "bulefire_fox"
}

###

POST http://localhost:8080/vc/hh
Authorization: 123456789
Content-Type: application/json

{
  "qID":"ABC123",
  "message": "hh"
}

###
POST http://localhost:8080/vc/blind
Authorization: 123456789
Content-Type: application/json

{

  "qqID":"ABC123",
  "code": "3K9L5LGX"
}